### ISSUE TITLE
Does this plug-in support versioning?

### ISSUE THREAD

**Issue by bambooyzj** [samaxes/minify-maven-plugin#113]
Is there a way to set up versioning while minifying?

**Comment by jieryn** [comment]
Unless it can also update your html which includes the versioned minified output, this seems useless.

**Comment by samaxes** [comment]
I can easily see two options to achieve this:

1. Use a suffix (`<suffix>.min-v1.0.0</suffix>`), but then you also need to update the file name in your HTML files (`<script src="/path/to/script.min-v1.0.0.js"></script>`)
1. Use the version as a query param in your script src (`<script src="/path/to/script.min.js?v1.0.0"></script>`), this way you don't need to change anything on the plugin configuration and you can bypass caching issues because every time you change the version, the browser consider it a new file and will always get the new version from the server
